### PR TITLE
Refactor of plugin

### PR DESCRIPTION
**Pull request by justindirose**

### CODE REVIEW

**Comment by justindirose** [comment]
@eviltrout I made all the suggested changes in the latest commit. Some of these things I didn't know were possible (i.e. `link-to`) and others were oversights on my part. Thanks for taking a look!

**Comment by justindirose** [comment]
@eviltrout I added some logic now for loading more topics.

It feels hacky since we're filtering after the `latest_results` query fires. Basically it will keep trying to load topics even if there are no filtered results because it can't see ahead. Example: If there are only 15 results tagged with "test-tag" that are in the selected KE categories/tags, it will try to query ALL latest topics to find those, instead of just the items that match the filters, and will keep doing so until the end of the list is hit (obviously not ideal). 

I have a couple possible solutions:

1. Append a custom filter into the TopicQuery library ([similar to this](https://github.com/procourse/procourse-installer/blob/b01455bbde97f1493d8b9f3f13889793b9bd6e4c/plugin.rb#L23-L116)). I'm not sure if this is the most stable approach, but it would let us use the protected functions in TopicQuery to generate our own list a bit more carefully. I think this is probably the best approach, but I don't know if it's acceptable.
2. Create our own custom topic query exclusively for the knowledge explorer. A lot of work but it would give us what we want.
3. Up the topics load to something higher, like 200. This will reduce the number of calls, but it's not a real solution and still breaks when there are a lot of topics in the KB.

Thoughts on approach here?

The Ember side seems to work ok, but I'm not really sure if there's a better way to do it. My understanding of Ember here is limited.

I also realize I'm counting tags only off the segmented lists, so those are not accurate either. That'll need some revising, but will have to come after figuring out the topic query bit.

**Comment by eviltrout** [comment]
> and will keep doing so until the end of the list is hit (obviously not ideal).

Can you point me to this part of the code?

It's a problem if we are repeatedly making new queries. If we are only querying once it's probably not a big deal.

**Comment by justindirose** [comment]
This line returns the first 30 results of latest (or whatever page is passed in via params)

https://github.com/discourse/discourse-knowledge-explorer/blob/163f08357dc3451f5fd93776f8a8c79e43e5b31d/lib/knowledge_explorer/query.rb#L21

The rest of the query filters those 30 results down to the topics that match our criteria.

Here, we determine if we should load more or not by adding a load more link with an incremented page number.

https://github.com/discourse/discourse-knowledge-explorer/blob/163f08357dc3451f5fd93776f8a8c79e43e5b31d/lib/knowledge_explorer/query.rb#L58-L60

The problem is not necessarily in the logic of the code here, but the structure of how we're pulling it.

Say we have 200 topics total we can access via the latest_results query, and only 15 of those match the selected filters. Assume those 15 topics are in the first two queries. In this instance, the loadMore function will fire 5 more times without the API returning any data (while still querying for the next paginated chunks of the latest_results query) because we don't have a way to know we're at the end of the filtered list, only the latest list.

For a site with 15,000+ topics like dev, or 130,000+ like meta, that's probably not ideal.

**Comment by justindirose** [comment]
@eviltrout I've made a number of changes to this now that I've gotten the load more functionality sorted out. Can you or someone else give it another once-over to see if I'm making any enormous errors?

**Pull request merged**
