### PR TITLE
FEATURE: Rename from Knowledge Explorer to Docs

### PR DESCRIPTION
**Pull request by justindirose**
Purely cosmetic PR. After internal discussion, the team decided to rename this plugin to `discourse-docs`.

A few implications that may need sorted:
- Site settings do not get migrated over because we've renamed them. I *think* this could be handled by a migration to copy the rows over. 
- I currently have the imports of the `Docs` Ember model following the path of `discourse-docs`, but this will require the repository is renamed as well, which has other implications I believe.

### CODE REVIEW

**Comment by ZogStriP** [comment]
> * Site settings do not get migrated over because we've renamed them. I _think_ this could be handled by a migration to copy the rows over.

Yup. There probably are examples in core.

**Comment by justindirose** [comment]
Added a settings migration today, so that should be okay to go. I believe front-end tests are failing here because of the repo name difference.

**Review by eviltrout — APPROVED** [review]
The change itself seems sound.

One thing we should consider is this is a big breaking change. If any plugins or themes are built on top of the plugin they will likely break. We should be careful merging if any customers/big users of discourse will be affected.

**Comment by justindirose** [comment]
>One thing we should consider is this is a big breaking change. If any plugins or themes are built on top of the plugin they will likely break. We should be careful merging if any customers/big users of discourse will be affected.

Fully agree. I'll do some digging but will start by posting to Meta about this change to give a heads up.

**Pull request merged**
